rolling_window: false
update_frequency: 10.0
publish_frequency: 0.1
# width: 5.0
# height: 5.0
resolution: .025
global_frame: map
robot_base_frame: humans_frame
#transform_tolerance: 15
footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.0]]
origin_x: -100.0
origin_y: -100.0
# plugins:
#  - {name: static_map, type: "costmap_2d::StaticLayer"}
#  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
#  - {name: inflater, type: "costmap_2d::InflationLayer"}
# obstacles:
#     observation_sources: /scan
#     /scan: {data_type: LaserScan, sensor_frame: /laser_front_link, marking: true, clearing: true, obstacle_range: 6, raytrace_range: 2}
#    track_unknown_space: true
